name: Ejemplo CI/CD

on: [push]

jobs:
  inicio:
    runs-on: windows-latest
    #Pasos
    steps:
      - name: mostrar texto
        run: echo "Hola Mundo"

  bluid:
    runs-on: windows-latest
    needs: [inicio]
    steps:
      - name: texto
        run: echo "Construir"

  bluid:
    runs-on: windows-latest
    needs: [build]
    steps:
      - name: texto
        run: echo "test"
  
  bluid:
    runs-on: windows-latest
    needs: [test]
    steps:
      - name: texto
        run: echo "Desplegar"
